### ISSUE TITLE
Runnig the vscode container

### ISSUE THREAD

**Issue by Haseenah01** [pubkey/vscode-in-docker#3]
Good day @pubkey and all, I trust you are well! When running the container with command: `docker run -p 8443:8443 -p 8888:8888 --volume /run/dbus/system_bus_socket:/run/dbus/system_bus_socket -v $(pwd)/data:/data -v $(pwd)/code:/code  --rm -it example-vscode`,  it is giving me this issue: 

`[27:0425/112449.059802:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[27:0425/112449.059844:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.`

The DISPLAY environment is present within the Dockerfile but it still says this.

I am just really having a hard time to run the vscode image itself.

**Comment by pubkey** [comment]
Hi.
Sorry I cannot give tech support here. Please do not @ me.
